apiVersion: v1
kind: Service
metadata:
  name: tiamat-fastapi-nginx-app
spec:
  type: LoadBalancer
  selector:
    app: tiamat-fastapi-nginx-app
  ports:
  - port: 8080              # Service listens on port 8000
    targetPort: 80          # Forwards to pod port 80
