version: '3.8'

services:
  fastapi:
    build:
      context: ./app
    container_name: fastapi
    restart: unless-stopped
    expose:
      - "8000"

  nginx:
    image: nginx:1.25-alpine
    container_name: nginx
    depends_on:
      - fastapi
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/html:/usr/share/nginx/html:ro
