---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-config
data:
  mongod.conf: |
    storage:
      dbPath: /data/db
    replication:
      replSetName: rs0
    net:
      bindIp: 0.0.0.0
      port: 27017
    systemLog:
      destination: file
      logAppend: true
      path: /var/log/mongodb/mongod.log
    processManagement:
      fork: false
    security:
      authorization: disabled
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-init-script
data:
  init-replica-set.js: |
    rs.initiate({
      _id: "rs0",
      members: [
        { _id: 0, host: "mongo-0.mongo:27017" },
        { _id: 1, host: "mongo-1.mongo:27017" },
        { _id: 2, host: "mongo-2.mongo:27017" }
      ]
    });
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    name: mongo
spec:
  ports:
  - port: 27017
    targetPort: 27017
  clusterIP: None
  selector:
    role: mongo
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
spec:
  serviceName: "mongo"
  replicas: 3
  selector:
    matchLabels:
      role: mongo
  template:
    metadata:
      labels:
        role: mongo
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mongo
        image: mongo:8.0
        command: ["mongod", "--config", "/etc/mongo/mongod.conf"]
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: ""
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: ""
        volumeMounts:
        - name: mongo-config
          mountPath: /etc/mongo
        - name: mongo-data
          mountPath: /data/db
        - name: mongo-logs
          mountPath: /var/log/mongodb
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        readinessProbe:
          exec:
            command:
            - mongosh
            - --eval
            - "db.adminCommand('ping')"
          initialDelaySeconds: 10
          periodSeconds: 5
      volumes:
      - name: mongo-config
        configMap:
          name: mongo-config
      - name: mongo-logs
        emptyDir: {}
  volumeClaimTemplates:
  - metadata:
      name: mongo-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: mongo-init-replica-set
spec:
  template:
    spec:
      containers:
      - name: mongo-init
        image: mongo:8.0
        command:
        - /bin/bash
        - -c
        - |
          echo "Waiting for MongoDB pods to be ready..."
          sleep 30
          echo "Initializing replica set..."
          mongosh --host mongo-0.mongo:27017 --eval '
          try {
            rs.status();
            print("Replica set already initialized");
          } catch (e) {
            if (e.message.includes("no replset config has been received")) {
              rs.initiate({
                _id: "rs0",
                members: [
                  { _id: 0, host: "mongo-0.mongo:27017" },
                  { _id: 1, host: "mongo-1.mongo:27017" },
                  { _id: 2, host: "mongo-2.mongo:27017" }
                ]
              });
              print("Replica set initialized successfully");
            } else {
              print("Error:", e.message);
            }
          }
          '
      restartPolicy: OnFailure
  backoffLimit: 5