apiVersion: v1
kind: Pod
metadata:
  name: fastapi-nginx-app-v2
  labels:
    app: fastapi-nginx-app-v2
    environment: development
    version: v2
spec:
  containers:
  - name: task-manager
    image: caedesaeterna/fastapi-nginx:v2
    ports:
    - containerPort: 80
      name: http
    resources:
      requests:
        memory: "32Mi"
        cpu: "50m"
      limits:
        memory: "128Mi"
        cpu: "300m"
    volumeMounts:
    - name: data-volume
      mountPath: /opt/app/data
  volumes:
  - name: data-volume
    emptyDir: {}
