apiVersion: v1
kind: Service
metadata:
  name: task-manager-service
  labels:
    version: v2
spec:
  type: LoadBalancer
  selector:
    app: fastapi-nginx-app-v2
  ports:
  - port: 8080              # Service listens on port 8080
    targetPort: 80          # Forwards to pod port 80
    name: http
