apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: webserver
    environment: development
spec:
  containers:
  - name: nginx
    image: nginx:1.27
    ports:
    - containerPort: 80
      name: http
    resources:
      requests:
        memory: "12Mi"
        cpu: "150m"
      limits:
        memory: "128Mi"
        cpu: "500m"
